[[track]]
path = "https://www.youtube.com/watch?v=Dvwaq1rwioQ"
title = "CITADEL Mountain Outpost | Relaxing Sci-Fi Ambience for Focus & Sleep 4K"
artist = "Ambient Outpost"
year = 2025
genre = "Ambient"
duration_secs = 7200

[[track]]
path = "https://www.youtube.com/watch?v=UnaXM6ceHks"
title = "ALONE: The Empty Outpost [Dark Ambient Focus Music] アローン: 空の前哨基地 - アンビエント ミュージック"
artist = "Ambient Outpost"
year = 2024
genre = "Ambient"
duration_secs = 7200

[[track]]
path = "https://www.youtube.com/watch?v=29S2rWCH1SU"
title = "ALONE: Winter Mission Outpost 2 | Dark Ambient Focus Music 4K"
artist = "Ambient Outpost"
year = 2024
genre = "Ambient"
duration_secs = 7207

[[track]]
path = "https://www.youtube.com/watch?v=bNmP4NsYgRI"
title = "ALONE: Dark Forest | Deep Ambient Focus Music 4K"
artist = "Ambient Outpost"
year = 2024
genre = "Ambient"
duration_secs = 7200

[[track]]
path = "https://www.youtube.com/watch?v=GGw3axV7IGs"
title = "NEVER Leave | Dark Ambient Focus Music 4K [ALONE]"
artist = "Ambient Outpost"
year = 2024
genre = "Ambient"
duration_secs = 7200

[[track]]
path = "https://www.youtube.com/watch?v=1fDP9T9Cagg"
title = "Echo Station | Deep Sci-Fi Outpost Ambience for Focus & Calm [4K]"
artist = "Ambient Outpost"
year = 2025
genre = "Ambient"
duration_secs = 7200

[[track]]
path = "https://www.youtube.com/watch?v=OovWK64WOTs"
title = "Hibernation Outpost [ALONE] Dark Ambient Focus Music 4K"
artist = "Ambient Outpost"
year = 2024
genre = "Ambient"
duration_secs = 10801

[[track]]
path = "https://www.youtube.com/watch?v=hSwcHHPcw2o"
title = "SILENT Watch | Mysterious Sci-Fi Ambience for Focus, Study & Sleep 4K"
artist = "Ambient Outpost"
year = 2025
genre = "Ambient"
duration_secs = 7200

[[track]]
path = "https://www.youtube.com/watch?v=vVf3Unl1Re0"
title = "Abandoned SCP Base | Dark Ambient Rain Music [4K]"
artist = "Ambient Outpost"
year = 2025
genre = "Ambient"
duration_secs = 3600

[[track]]
path = "https://www.youtube.com/watch?v=gb6lKl8c9cg"
title = "CONSPIRACY [Black Projects 5] Dark Ambient Focus Music 4K"
artist = "Ambient Outpost"
year = 2024
genre = "Ambient"
duration_secs = 10800
