[[track]]
path = "https://youtu.be/G50osETXg78"
title = "Overture"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 1
duration_secs = 161

[[track]]
path = "https://youtu.be/R6F0qUL6kSk"
title = "Object Permanence"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 2
duration_secs = 230

[[track]]
path = "https://youtu.be/mQJy217s75I"
title = "Aries (Moth Song)"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 3
duration_secs = 190

[[track]]
path = "https://youtu.be/hgbMVcGhng0"
title = "Tough Love"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 4
duration_secs = 198

[[track]]
path = "https://youtu.be/c49swjLE2EY"
title = "Formative Age"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 5
duration_secs = 233

[[track]]
path = "https://youtu.be/H30HRwb6-QA"
title = "Muscle Memory"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 6
duration_secs = 206

[[track]]
path = "https://youtu.be/R02B_L2MAcg"
title = "Playing Mercy"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 7
duration_secs = 191

[[track]]
path = "https://youtu.be/r_B9NJocXGI"
title = "Everything As I Knew It"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 8
duration_secs = 165

[[track]]
path = "https://youtu.be/VPsVifXOcNA"
title = "In Loving Memory"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 9
duration_secs = 224

[[track]]
path = "https://youtu.be/ZD2ENf8XwaQ"
title = "Family And Friends"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 10
duration_secs = 178

[[track]]
path = "https://youtu.be/hZthHM57sIA"
title = "Dirge"
artist = "Arm's Length"
album = "Never Before Seen, Never Again Found"
year = 2022
track_number = 11
duration_secs = 320
