[[track]]
path = "https://www.youtube.com/watch?v=nv_zu4zn2Vo"
title = "Dark DnB High Energy Intense Focus Workout Music, Audio Sugar Rush - Isochronic Tones"
artist = "Jason Lewis - Mind Amend"
year = 2023
genre = "Drum and Bass"
duration_secs = 3600
