[[track]]
path = "https://www.youtube.com/watch?v=cu_vihKMWeA"
title = "Synthwave Coding Mix – Feels Like 𝐓𝐄𝐑𝐌𝐈𝐍𝐀𝐋 𝟏𝟗𝟖𝟕 Never Closed"
artist = "Devs FM"
year = 1987
genre = "Synthwave"
duration_secs = 7181

[[track]]
path = "https://www.youtube.com/watch?v=knbaRZMVD1s"
title = "Vaporwave Coding Mix Vol II - Feels Like We’re BACK TO 1984"
artist = "Devs FM"
year = 1984
genre = "Vaporwave"
duration_secs = 5455

