[[track]]
path = "https://www.youtube.com/watch?v=M-ZHRVUlRz0"
title = "𝙻𝙾𝚂𝚃 𝙸𝙽 𝟷𝟿𝟾𝟸."
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 4286

[[track]]
path = "https://www.youtube.com/watch?v=nbcmNwS0YqQ"
title = "ＤＲＥＡＭＳ　ＡＦＴＥＲ　ＷＯＲＫ"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 3974

[[track]]
path = "https://www.youtube.com/watch?v=0doATM2dsO8"
title = "ＰＥＡＣＥ　ＡＦＴＥＲ　ＨＯＵＲＳ"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 4396

[[track]]
path = "https://www.youtube.com/watch?v=SaQqHlryu4Y"
title = "ＣＩＧＡＲＥＴＴＥＳ　ＡＦＴＥＲ　ＷＯＲＫ"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 4078

[[track]]
path = "https://www.youtube.com/watch?v=ioS4-eJo8J8"
title = "ＤＲＥＡＭＳ　ＡＦＴＥＲ　ＷＯＲＫ　ＩＩ"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 4148

[[track]]
path = "https://www.youtube.com/watch?v=hZNWl-tGCxQ"
title = "ＦＥＬＬ　ＡＳＬＥＥＰ　ＩＮ　１９８４"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 5040

[[track]]
path = "https://www.youtube.com/watch?v=CPpLRzFdz7g"
title = "ＤＲＥＡＭＳ　ＡＦＴＥＲ　ＷＯＲＫ　ＩＩＩ"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 4099

[[track]]
path = "https://www.youtube.com/watch?v=YSjv3C581S8"
title = "ＣＯＲＰＯＲＡＴＥ　ＤＲＥＡＭＳ　１９９１"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 4212

[[track]]
path = "https://www.youtube.com/watch?v=Zjk8SuQcWJE"
title = "ＰＥＡＣＥ　ＡＦＴＥＲ　ＨＯＵＲＳ　１９９１"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 3937

[[track]]
path = "https://www.youtube.com/watch?v=4GCj1GQluRc"
title = "𝚁𝙴𝚆𝙸𝙽𝙳 𝚃𝙾 𝟷𝟿𝟾𝟹.  // 𝙋𝙞𝙭𝙚𝙡𝙬𝙖𝙫𝙚 ~ 𝙎𝙮𝙣𝙩𝙝𝙬𝙖𝙫𝙚 ~ 𝙑𝙖𝙥𝙤𝙧𝙬𝙖𝙫𝙚"
artist = "dream.surfer"
year = 2025
genre = "Vaporwave"
duration_secs = 4093
