[[track]]
path = "https://www.youtube.com/watch?v=0NCrui_dYJY"
title = "💻 founder mode | 9-5 escape | dark ambient for building at 3am"
artist = "lock in music."
year = 2025
genre = "Ambient"
duration_secs = 3637

[[track]]
path = "https://www.youtube.com/watch?v=zF-j5u1CoAo"
title = "god complex • dark phonk mix for unstoppable focus (1 hour)"
artist = "lock in music."
year = 2025
genre = "Phonk"
duration_secs = 3701

[[track]]
path = "https://www.youtube.com/watch?v=qlM39cB_5hk"
title = "soft dark ambient | instrumental beats to code to (1h non-stop)"
artist = "lock in music."
year = 2025
genre = "Ambient"
duration_secs = 3788

[[track]]
path = "https://www.youtube.com/watch?v=I1ksORM1DDI"
title = "🌃 3am lock in ambient | founder flow state | 9-5 escape"
artist = "lock in music."
year = 2025
genre = "Ambient"
duration_secs = 3754

[[track]]
path = "https://www.youtube.com/watch?v=kvk1hahaKE8"
title = "zero mercy • dark phonk mix for ruthless focus (1 hour)"
artist = "lock in music."
year = 2025
genre = "Phonk"
duration_secs = 3644

[[track]]
path = "https://www.youtube.com/watch?v=_CHFV_mt03M"
title = "discipline mode • dark phonk mix for unstoppable work sessions (1 hour)"
artist = "lock in music."
year = 2025
genre = "Phonk"
duration_secs = 3660

[[track]]
path = "https://www.youtube.com/watch?v=7ERfXi19vK4"
title = "no mercy mode • 1 hour dark phonk focus mix"
artist = "lock in music."
year = 2025
genre = "Phonk"
duration_secs = 3813

[[track]]
path = "https://www.youtube.com/watch?v=90cCAAdwlNc"
title = "lock in at 2am - dark ambient for focus & flow"
artist = "lock in music."
year = 2025
genre = "Ambient"
duration_secs = 3783

[[track]]
path = "https://www.youtube.com/watch?v=H9IZSBKeWMk"
title = "slow grind mode • 1 hour dark ambient phonk (no mercy mix)"
artist = "lock in music."
year = 2025
genre = "Phonk"
duration_secs = 3740

[[track]]
path = "https://www.youtube.com/watch?v=ihHCAiAgcA8"
title = "midnight focus sessions | dark electronic beats for for deep work (1h non-stop)"
artist = "lock in music."
year = 2025
genre = "Electronic"
duration_secs = 3694
