[[track]]
path = "https://www.youtube.com/watch?v=foRK-FHIXaE"
title = "Ryan Gosling driving with Nightcall by Kavinsky for 4 hours"
artist = "FactMojo"
year = 2024
genre = "Synthwave"
duration_secs = 14232
