[[track]]
path = "https://www.youtube.com/watch?v=cu_vihKMWeA"
title = "Synthwave Coding Mix – Feels Like 𝐓𝐄𝐑𝐌𝐈𝐍𝐀𝐋 𝟏𝟗𝟖𝟕 Never Closed"
artist = "Devs FM"
year = 1987
genre = "Synthwave"
duration_secs = 7181
