[[track]]
path = "https://youtu.be/tt2zUFXf6XE?si=tPBigmGozaeyNfoc"
title = "American Dream"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 1
duration_secs = 209

[[track]]
path = "https://youtu.be/pVEs--10Vb0?si=Ca2539aQ7yIIijM6"
title = "The Getaway"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 2
duration_secs = 275

[[track]]
path = "https://youtu.be/Ih9XednpDZI?si=0hPZH8wpXSkGNY8N"
title = "Just Like Paradise"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 3
duration_secs = 213

[[track]]
path = "https://youtu.be/__g3YlWUicE?si=ys5ICrS8JI0KFC_H"
title = "Down"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 4
duration_secs = 213

[[track]]
path = "https://youtu.be/zFXCXT4KDW4?si=tHEJmb33tZOaW6Er"
title = "Soundtrack"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 5
duration_secs = 228

[[track]]
path = "https://youtu.be/JuFln_QdLJo?si=J867sqmN7OVmGCsl"
title = "Kids of the Last Days"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 6
duration_secs = 212

[[track]]
path = "https://youtu.be/5qaF6_gFffA?si=AasreNodbc0sAiz2"
title = "Heroes of the Heart"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 7
duration_secs = 229

[[track]]
path = "https://youtu.be/2898ZuGghPw?si=UHJsPMTmV_mWmU6-"
title = "Just Friends"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 8
duration_secs = 217

[[track]]
path = "https://youtu.be/SlVvAgyeEx8?si=JJi5JmL3z63YyYLP"
title = "I Wish That You Would"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 9
duration_secs = 249

[[track]]
path = "https://youtu.be/ytloFR7WOq4?si=ogbNikizKxUnFFxw"
title = "Reckless"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 10
duration_secs = 222

[[track]]
path = "https://youtu.be/eDDbeH9h0XQ?si=m2Z6v37oZqb8499E"
title = "Until the Lights Go Out"
artist = "The Strike"
album = "A Dream Through Open Eyes"
year = 2024
track_number = 11
duration_secs = 287
