[[track]]
path = "https://www.youtube.com/watch?v=GW3B30KQczs"
title = "ＬＡＴＥ    ＮＩＧＨＴ   ＣＨＩＬＬ   ２"
artist = "utopic.dreamer"
year = 2025
genre = "Vaporwave"
duration_secs = 21723

[[track]]
path = "https://www.youtube.com/watch?v=Yf7-z6P9Q94"
title = "ＢＡＣＫ ＴＯ ＴＨＥ ８０ｓ // calm vaporwave ~ ambient dreamwave mix"
artist = "utopic.dreamer"
year = 2024
genre = "Vaporwave"
duration_secs = 21103

[[track]]
path = "https://www.youtube.com/watch?v=kNq5zKoYfc8"
title = "𝙄𝙩'𝙨 𝟰 𝙖.𝙢 𝙞𝙣 𝟭𝟵𝟴𝟳 𝙖𝙣𝙙 𝙮𝙤𝙪 𝙘𝙖𝙣'𝙩 𝙨𝙡𝙚𝙚𝙥."
artist = "utopic.dreamer"
year = 2025
genre = "Vaporwave"
duration_secs = 18135

[[track]]
path = "https://www.youtube.com/watch?v=AcQ3Di2Gewc"
title = "𝙄𝙩'𝙨 𝟭𝟵𝟴𝟳 𝙖𝙣𝙙 𝙮𝙤𝙪 𝙨𝙩𝙖𝙮𝙚𝙙 𝙡𝙖𝙩𝙚 𝙖𝙩 𝙩𝙝𝙚 𝙤𝙛𝙛𝙞𝙘𝙚 // officewave, vaporwave, chillwave"
artist = "utopic.dreamer"
year = 2025
genre = "Vaporwave"
duration_secs = 18457

[[track]]
path = "https://www.youtube.com/watch?v=QDF26jiK2-s"
title = "ＩＴ`Ｓ ＡＬＷＡＹＳ ４ ＡＭ"
artist = "utopic.dreamer"
year = 2025
genre = "Vaporwave"
duration_secs = 18113

[[track]]
path = "https://www.youtube.com/watch?v=kmsCOmvsR14"
title = "𝘐𝘵'𝘴 1994 𝘢𝘯𝘥 𝘦𝘷𝘦𝘳𝘺𝘰𝘯𝘦 𝘪𝘴 𝘢𝘴𝘭𝘦𝘦𝘱, 𝘦𝘹𝘤𝘦𝘱𝘵 𝘺𝘰𝘶 // calm dreamwave ~ ambient vaporwave playlist"
artist = "utopic.dreamer"
year = 2026
genre = "Vaporwave"
duration_secs = 18221

[[track]]
path = "https://www.youtube.com/watch?v=O5-WIDPNrFk"
title = "ＬＡＴＥ ＮＩＧＨＴ ＣＨＩＬＬ"
artist = "utopic.dreamer"
year = 2024
genre = "Vaporwave"
duration_secs = 23255

[[track]]
path = "https://www.youtube.com/watch?v=80Zv7K3LaUU"
title = "ＬＡＴＥ ＮＩＧＨＴ ＷＯＲＫ //  Nostalgic Officewave ~ Calm Vaporwave"
artist = "utopic.dreamer"
year = 2024
genre = "Vaporwave"
duration_secs = 21738

[[track]]
path = "https://www.youtube.com/watch?v=OLS9yCmYfNw"
title = "𝙞𝙩'𝙨 𝟭𝟵𝟵𝟯 𝙖𝙣𝙙 𝙚𝙫𝙚𝙧𝙮𝙤𝙣𝙚 𝙞𝙨 𝙖𝙨𝙡𝙚𝙚𝙥, 𝙚𝙭𝙘𝙚𝙥𝙩 𝙮𝙤𝙪 // calm dreamwave ~ ambient vaporwave playlist"
artist = "utopic.dreamer"
year = 2024
genre = "Vaporwave"
duration_secs = 21909

[[track]]
path = "https://www.youtube.com/watch?v=nRh6NVFf0uk"
title = "𝙡𝙞𝙫𝙞𝙣𝙜 𝙩𝙝𝙚 𝙙𝙧𝙚𝙖𝙢 𝙞𝙣 𝟭𝟵𝟵𝟲 // 𝙛𝙖𝙨𝙩 𝙫𝙖𝙥𝙤𝙧𝙬𝙖𝙫𝙚 𝙢𝙞𝙭"
artist = "utopic.dreamer"
year = 2024
genre = "Vaporwave"
duration_secs = 21600
