
[[track]]
path = "https://youtu.be/xSo0Vp-xwAI?si=qHvKbAE-2VbE1nPv"
title = "music that feels like it's 2003"
artist = "Mik4000"
year = 2003
genre = "Vaporwave"
duration_secs = 3726

[[track]]
path = "https://youtu.be/RfB7y7M6P4c?si=f-xjMeaqB_kJR6QA"
title = "𝗚𝗢𝗗 𝗢𝗡 𝗧𝗛𝗘 𝗖𝗢𝗗𝗘 碼神 | 1990s Ambient Vaporwave"
artist = "Liminal Stages"
year = 1990
genre = "Vaporwave"
duration_secs = 14406

[[track]]
path = "https://www.youtube.com/watch?v=knbaRZMVD1s"
title = "Vaporwave Coding Mix Vol II - Feels Like We’re BACK TO 1984"
artist = "Devs FM"
year = 1984
genre = "Vaporwave"
duration_secs = 5455
